services:
  myplantuml:
    image: plantuml/plantuml-server:v1.2025.2
    ports:
      - "8080:8080"
  plantuml-mcp-server-sse:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "3000:3000"
    environment:
      - PlantUmlBaseUrl=http://myplantuml:8080/
    command:
      # Use the following for Debug mode:
      # [ "dotnet", "run", "--project", "plantuml-mcp-server-sse/plantuml-mcp-server-sse.csproj", "--", "PlantUmlBaseUrl=$PlantUmlBaseUrl" ]

      # Use the following for Production mode:
      [ "dotnet", "run", "--project", "plantuml-mcp-server-sse/plantuml-mcp-server-sse.csproj", "--configuration", "Release", "--", "PlantUmlBaseUrl=$PlantUmlBaseUrl" ]
