name: Build And Push Container Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Container image tag'
        required: true
        default: 'manual-test'
        type: string

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # イメージをプッシュする権限をGITHUB_TOKENに付与する
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # .NET SDKのセットアップ
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    # 1. ghcrにログインする
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # 2. .NETコンテナイメージをビルド・pushする
    - name: Build and Push .NET Container
      run: |
        dotnet publish -t:PublishContainer ./plantuml-mcp-server-stdio/plantuml-mcp-server-stdio.csproj \
        -p:ContainerRegistry=${{ env.REGISTRY }} \
        -p:ContainerRepository=${{ env.REGISTRY }}/${{ github.repository_owner }}/plantuml-validator-mcp-server \
        -p:ContainerImageTag=${{ inputs.tag || github.ref_name }}
      env:
        CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}